version: '3'

services:
    bot:
        build: .
        links:
            - db
        env_file: 
            - ".env_app"
        ports: 
            - 5000:5000     # host:container

    db:
        image: mysql
        restart: always
        command: ["--default-authentication-plugin=mysql_native_password"]
        env_file:
            - ".env_mysql"